language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: zepmanbc
  password:
    secure: f+qgKKjw6Cfz5nQwmrvxqemX6VPmxgD9EEjXK8Adx3ZyR95z8zSGnNsG/AmBGYZYThQn8GFF6Ypq15EfGXLsc3uarQMN39nN/pXHvi/jqOBs3pq3bSrNq4ZBV4QaCB3v5vh5YD/eT4GEXZ6KYh9hMniak13md/CZFBmqAzkbQ2bjqeE8wko+fj6CT2y8lmwLgEnJa++Bmhob4XF/pakgR2cI2euwnmUbutej1i7j38VdDnxfDh5Ory61YMprwEfZV6l0nn5i1Vx0WT09yKSAS5yyC+vudz6r2g2jD1ngsInnToY5HwmaIOseit7i8qlEgW11scax+aR+u3n2r2cbcq/gIfbsurn/Z40Mfec/IVpM32Yzmnz+FZEM+8H7lVYuBFDJrgQGPeMM8RfcEKidWih4oZKj+APHFbmhnmz7xokMsLZnanh1qp8tdGA95RUpUBtGklWLKkS8B9qA9CYx8EiTdmx6L2wFFq+60Ph9JslYXtZlxlRV7AJV6iBo/evlatfog8ChaTuhH8hO1a9REj6iLanWUKpEDi2gZ+l1nDlHOaG0rANg9+aY02WCEtC43dlMI2YtkQP7r3eokwAVwjO2xTiIjalJ+HtnQaPeYBuEhjGXs+OotEvkBhjKHEI6Wl//wbt3U3du4xHgmXDNHJIHRNk8ik/IofX/XUkggas=
  on:
    tags: true
    repo: zepmanbc/cookiecutterpackage
    python: 3.6
